//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Velyo.AspNet.Markdown.Samples {
    
    
    public partial class Page2 {
        
        /// <summary>
        /// sample2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Velyo.AspNet.Markdown.MarkdownContent sample2;
    }
}
